spring:
  rabbitMq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

jwt:
  key: "-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQCCepvCf316MOq1kyrp2PQRYylqRo0FAWKAmwifr//g4BISa5Gf
V6ZrVCA4ZiGTn6HyvHWlbI1CmrVo3Tp2a2qvhAhjSQdpYP7ArR6riLeJrD3wTzlE
jFhXuI1iBGrLwJRkXnVPI8IFeUFqqqbPi0P1pi/XkzGkZH9RvOezcsgMiQIDAQAB
AoGANvy61a3q0Gr7Dwh1ZlWjDgzPMFWJKpnZzD8J1FpUqI1lsFOa7B8BKGwso/gO
oGr+0hAwOEXWBkKyvv20nKFKNQ339IzR1trZBUXrh/qR9jksJLfAAvNrfnyku39d
tr0hqvgx3IUUZhuW5Y4dRFUGZ9WgGrXOw4IIeIx+uC+zJj0CQQDiwvFl5v53upyS
+DpJukgy91jlDKD/g6T3886RoUO9m5BgjAZAZ2OibW7P2jlT64SSJh8o5Jc6tFfO
OQF3mbSHAkEAk02FyjCAmCBtMElLb9scWafl86nnFHWxKoO36WHDmnOAi2KjCexK
4LCyCVJjwM6RIU/MzszXBmdzKWO/zB6KbwJAT7ZzoXzIK1KAQ/Ham5xOUQw+RZZg
6jFexoMANJVZ+Mc8w5O1huJRVgHeGFcAHA4Itk+MWJWyy8Ils6q6Z06y9QJALIFa
r/kxkUUS2Gj8wuIH0crZvmISMGtSyQ6dDYV9TPgi2XpG2mOrR/H7CLf87a87yD3N
GppnSUcOU24Q8AI2PwJBAMNWR661lQ+69OPy1NKkmac/pLlJqoDfL6WoJA+So9kz
fbYjRrSuvvoeSkGb7hX8OIM6h85cl3tDAINWFIj3H/Q=
-----END RSA PRIVATE KEY-----"
  publicKey: "-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCepvCf316MOq1kyrp2PQRYylq
Ro0FAWKAmwifr//g4BISa5GfV6ZrVCA4ZiGTn6HyvHWlbI1CmrVo3Tp2a2qvhAhj
SQdpYP7ArR6riLeJrD3wTzlEjFhXuI1iBGrLwJRkXnVPI8IFeUFqqqbPi0P1pi/X
kzGkZH9RvOezcsgMiQIDAQAB
-----END PUBLIC KEY-----"
  issuer: test_issuer
  expire: 120
